# Generated by Django 4.2.4 on 2023-08-17 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_chatroom_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=950)),
                ('author', models.CharField(max_length=150)),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='message',
            field=models.ManyToManyField(blank=True, null=True, to='chatapp.messages'),
        ),
    ]
