# Generated by Django 4.2.4 on 2023-08-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_messages_chatroom_remove_messages_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='chatroom',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='message',
            field=models.ManyToManyField(blank=True, null=True, to='chatapp.messages'),
        ),
    ]
