# Generated by Django 4.2.4 on 2023-08-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_remove_messages_chatroom_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='message',
        ),
        migrations.AddField(
            model_name='messages',
            name='chatroom',
            field=models.ManyToManyField(blank=True, null=True, to='chatapp.chatroom'),
        ),
    ]
