# Generated by Django 4.2.4 on 2023-08-21 18:33

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0009_remove_chatroom_message_messages_chatroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('theUser', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
