# Generated by Django 4.2.4 on 2023-08-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_testermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TesterModel',
        ),
    ]
