# Generated by Django 4.2.4 on 2023-08-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0013_chatroom_createdby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TesterModel',
        ),
    ]
