# Generated by Django 4.2.4 on 2023-08-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0017_delete_killer_alter_messages_chatroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Killer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('killerName', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=3)),
            ],
        ),
    ]
