# Generated by Django 4.2.4 on 2023-08-26 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0020_delete_killer_alter_messages_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='createdBy',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
