# Generated by Django 4.2.4 on 2023-08-29 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0021_alter_chatroom_createdby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='createdBy',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
