# Generated by Django 4.2.4 on 2023-08-30 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0022_remove_chatroom_createdby_chatroom_createdby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='chatroom',
        ),
        migrations.AddField(
            model_name='messages',
            name='chatroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatapp.chatroom'),
            preserve_default=False,
        ),
    ]
