# Generated by Django 4.2.4 on 2023-08-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0025_alter_chatroom_createdby_alter_messages_chatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='chatroom',
        ),
    ]
