# Generated by Django 4.2.4 on 2023-08-30 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0026_remove_messages_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='chatroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='chatapp.chatroom'),
            preserve_default=False,
        ),
    ]
