# Generated by Django 4.2.4 on 2023-08-31 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0027_messages_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 31, 16, 49, 37, 524974)),
        ),
    ]
