# Generated by Django 4.2.4 on 2023-08-31 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0031_alter_messages_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
