# Generated by Django 4.2.4 on 2023-09-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0033_alter_chatroom_description_alter_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='nameslug',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
